name: Deployment

on: 
  push:
    branches: [main, staging]
  
jobs:
  deploy:
    name: Deploying...
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup environment variables
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "IS_STAGING=false" >> $GITHUB_ENV
          else
            echo "IS_STAGING=true" >> $GITHUB_ENV
          fi
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2`
        with:
          terraform_version: 1.7.0
          
      - name: Install dependencies...
        env:
          IS_STAGING: ${{ env.IS_STAGING }}
        run: |
          npm ci

      - name: Building static site...
        env:
          IS_STAGING: ${{ env.IS_STAGING }}
        run: |
          npm run export
        